name: advent_of_code_2023
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.2.2

dependencies:
#   path: ^1.8.0
  dart_advent_of_code_core: 1.0.0
  meta: ^1.11.0

dev_dependencies:
  lints: ^2.1.0
  test: ^1.24.0

dependency_overrides:
  dart_advent_of_code_core:
    path: ../dart_advent_of_code_core/

