name: advent_of_code_2023
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.2.2

dependencies:
#   path: ^1.8.0
  dart_advent_of_code_core: 1.0.0
  freezed_annotation: ^2.4.1
  meta: ^1.11.0

dev_dependencies:
  build_runner: ^2.4.7
  freezed: ^2.4.5
  lints: ^2.1.0
  test: ^1.24.0

dependency_overrides:
  dart_advent_of_code_core:
    path: ../dart_advent_of_code_core/

